name = "InferOpt"
uuid = "4846b161-c94e-4150-8dac-c7ae193c601f"
authors = ["Axel Parmentier", "Guillaume Dalle", "Léo Baty", "Louis Bouvier"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
